### ISSUE TITLE
`onyo init` fails when passed a non-existent directory

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#138]
I attempted the following:
```
(onyo) aqw@hrududu in /tmp
❱ onyo init tst
Traceback (most recent call last):
  File "/home/aqw/.venvs/onyo/bin/onyo", line 33, in <module>
    sys.exit(load_entry_point('onyo', 'console_scripts', 'onyo')())
  File "/home/aqw/git/inm7/onyo/onyo/main.py", line 429, in main
    args.run(args, onyo_root)
  File "/home/aqw/git/inm7/onyo/onyo/commands/init.py", line 63, in init
    git_init_command = build_git_init_cmd(directory)
  File "/home/aqw/git/inm7/onyo/onyo/commands/init.py", line 24, in build_git_init_cmd
    if is_git_dir(directory) and os.path.isdir(directory + "/.onyo"):
  File "/home/aqw/git/inm7/onyo/onyo/utils.py", line 39, in is_git_dir
    Repo(directory).git_dir
  File "/home/aqw/.venvs/onyo/lib/python3.10/site-packages/git/repo/base.py", line 152, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /tmp/tst
```
It did not create the directory.
```
(onyo) aqw@hrududu in /tmp
❱ ls -lah tst
ls: cannot access 'tst': No such file or directory
```

Onyo should create the dir and initialize it.

**Comment by aqw** [comment]
Re-opening, as #131 simply introduced an error, rather than creating a directory automatically (as it should).
