### ISSUE TITLE
BUG: `onyo new` chokes on invalid key=value pairs

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#410]
```
❱ onyo new -k type=laptop make=framework model=gen1 serial=sadkjfui234 BREAKME
Traceback (most recent call last):
  File "/home/aqw/.venvs/onyo/bin/onyo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aqw/git/inm7/onyo/onyo/main.py", line 290, in main
    args = parser.parse_args()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 1881, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 1914, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2108, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2085, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.11/argparse.py", line 1990, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.11/argparse.py", line 1253, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 1914, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2126, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2066, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.11/argparse.py", line 1990, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/aqw/git/inm7/onyo/onyo/argparse_helpers.py", line 30, in __call__
    register_dict = {k: [] for k, v in pairs}
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aqw/git/inm7/onyo/onyo/argparse_helpers.py", line 30, in <dictcomp>
    register_dict = {k: [] for k, v in pairs}
                               ^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by bpoldrack** [comment]
Fixed in #415:

```
❱ onyo new -k type=laptop make=framework model=gen1 serial=sadkjfui234 BREAKME                                                 2 !
usage: onyo new [-h] [-t TEMPLATE] [-e] [-k KEYS [KEYS ...]] [-p PATH] [-tsv TSV] [-m MESSAGE]
onyo new: error: Invalid argument 'BREAKME'. Expected key-value pairs '<key>=<value>'.
```
