### ISSUE TITLE
BUG: `onyo set` errors with no message when setting the same key twice in one call

### ISSUE THREAD

**Issue by aqw** [psyinfra/onyo#417]
```
(onyo) aqw@hrududu in /tmp/yope on git:master
❱ onyo set -k make=yup1 make=yup2 --rename -p dp/Alex\ Waite/laptop_framework_gen1.faux 
ERROR: 
```

**Comment by bpoldrack** [comment]
Note for fixing this: Here is the traceback:

```
ERROR: 
DEBUG:onyo:Traceback (most recent call last):
  File "/home/ben/work/hacking/onyo/onyo/main.py", line 302, in main
    args.run(args)
  File "/home/ben/work/hacking/onyo/onyo/commands/set.py", line 80, in set
    assert len(args.keys) == 1
           ^^^^^^^^^^^^^^^^^^^
AssertionError

```
