### ISSUE TITLE
BUG: `onyo set` errors on asset file names containing empty name fields (e.g. if make="")

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#419]
We allow `onyo new -k type= make= model= serial=faux --path warehouse` to create assets with names like `__.faux4yxQjP`, e.g. empty type, mkae, model.

But if then `onyo set` is called on it, it errors:
```
❱ onyo --debug set --keys RAM=101  --path warehouse/__.faux2Nk3yb                          1 !
DEBUG:onyo:Onyo repo found at '/Users/tkadelka/none-existing-folder'
DEBUG:onyo:Running 'git ['config', '--get', 'onyo.assets.filename']'
DEBUG:onyo:git config missed 'onyo.assets.filename'
DEBUG:onyo:Running 'git ['config', '--file', '/Users/tkadelka/none-existing-folder/.onyo/config', '--get', 'onyo.assets.filename']'
DEBUG:onyo:config 'onyo.assets.filename' acquired from /Users/tkadelka/none-existing-folder/.onyo/config: '{type}_{make}_{model}.{serial}'
DEBUG:onyo:Looking up tracked files
DEBUG:onyo:Running 'git ['ls-files', '-z']'
ERROR: list index out of range
DEBUG:onyo:Traceback (most recent call last):
  File "/Users/tkadelka/INM7/onyo/onyo/main.py", line 302, in main
    args.run(args)
  File "/Users/tkadelka/INM7/onyo/onyo/commands/set.py", line 83, in set
    onyo_set(inventory=inventory,
  File "/Users/tkadelka/INM7/onyo/onyo/lib/commands.py", line 594, in onyo_set
    asset_paths_to_set = [p for p, _ in get_assets_by_query(
  File "/Users/tkadelka/INM7/onyo/onyo/lib/commands.py", line 594, in <listcomp>
    asset_paths_to_set = [p for p, _ in get_assets_by_query(
  File "/Users/tkadelka/INM7/onyo/onyo/lib/assets.py", line 196, in <genexpr>
    for k, v in (get_asset_content(a) | asset_name_to_keys(a, PSEUDO_KEYS)).items()}) for a in assets)
  File "/Users/tkadelka/INM7/onyo/onyo/lib/filters.py", line 19, in asset_name_to_keys
    re.findall(r'(^[^._]+?)_([^._]+?)_([^._]+?)\.(.+)', path.name)[0]))
IndexError: list index out of range
```

**Comment by bpoldrack** [comment]
Actually the same as #424

**Comment by bpoldrack** [comment]
Closing in favor of #481
