### ISSUE TITLE
BUG: `onyo set` fails with 'list index out of range'

### ISSUE THREAD

**Issue by nhjjr** [psyinfra/onyo#424]
Command: 
```
onyo --debug set -k rating="6 out of 7 wonders" -p "7 Wonders (2010).fauxqsKN26"
```

Output:
```
DEBUG:onyo:Onyo repo found at '/home/niels/code/onyo-demo'
DEBUG:onyo:Running 'git ['config', '--get', 'onyo.assets.filename']'
DEBUG:onyo:git config missed 'onyo.assets.filename'
DEBUG:onyo:Running 'git ['config', '--file', '/home/niels/code/onyo-demo/.onyo/config', '--get', 'onyo.assets.filename']'
DEBUG:onyo:config 'onyo.assets.filename' acquired from /home/niels/code/onyo-demo/.onyo/config: '{title} ({year}).{serial}'
DEBUG:onyo:Looking up tracked files
DEBUG:onyo:Running 'git ['ls-files', '-z']'
ERROR: list index out of range
DEBUG:onyo:Traceback (most recent call last):
  File "/home/niels/.venv/onyo-demo/lib/python3.11/site-packages/onyo/main.py", line 302, in main
    args.run(args)
  File "/home/niels/.venv/onyo-demo/lib/python3.11/site-packages/onyo/commands/set.py", line 83, in set
    onyo_set(inventory=inventory,
  File "/home/niels/.venv/onyo-demo/lib/python3.11/site-packages/onyo/lib/commands.py", line 609, in onyo_set
    asset_paths_to_set = [p for p, _ in get_assets_by_query(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niels/.venv/onyo-demo/lib/python3.11/site-packages/onyo/lib/commands.py", line 609, in <listcomp>
    asset_paths_to_set = [p for p, _ in get_assets_by_query(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niels/.venv/onyo-demo/lib/python3.11/site-packages/onyo/lib/assets.py", line 196, in <genexpr>
    for k, v in (get_asset_content(a) | asset_name_to_keys(a, PSEUDO_KEYS)).items()}) for a in assets)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niels/.venv/onyo-demo/lib/python3.11/site-packages/onyo/lib/filters.py", line 19, in asset_name_to_keys
    re.findall(r'(^[^._]+?)_([^._]+?)_([^._]+?)\.(.+)', path.name)[0]))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

Template File (`.onyo/templates/boardgame`):
```
---
players:
time:
designer:
rating:  # some persistent comment
serial: faux
```

**Comment by bpoldrack** [comment]
Note to myself: Evidently, `set` uses the wrong `get_assets_by_query`, expecting a hardcoded naming scheme instead of the new config (hence `PSEUDO_KEYS` rather than `OnyoRepo.get_required_keys()`)
