### ISSUE TITLE
BUG: `onyo mv a/b/c/ a/d/c/` errors "already exists" instead of  `a/d/c/c/`

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#516]
AFAIK we allow the same name for multiple directories in an inventory.
However, when moving a directory `c` into another directory also named `c`, it does not lead to a directory `c/c/`, but instead onyo raises an error:

`onyo mv`:
```
❱ onyo mv a/b/c/ a/d/c/ 
ERROR: Target /Users/tkadelka/onyo/a/d/c already exists.
```
Normal `mv`:
```
❱ mv a/b/c/ a/d/c/                                                                         1 !
❱ ls a/d/c/
c
```

This is caused by `onyo_mv()` in `commands.py` going into the ` #MOVE special case`.

Traceback:
```
❱ onyo --debug mv a/b/c/ a/d/c/                                                            1 !
DEBUG:onyo:Onyo repo found at '/Users/tkadelka/onyo'
DEBUG:onyo:Looking up tracked files
DEBUG:onyo:Running 'git ls-files -z'
ERROR: Target /Users/tkadelka/onyo/a/d/c already exists.
DEBUG:onyo:Traceback (most recent call last):
  File "/Users/tkadelka/INM7/onyo/onyo/lib/commands.py", line 493, in move_asset_or_dir
    inventory.move_asset(source, destination)
  File "/Users/tkadelka/INM7/onyo/onyo/lib/inventory.py", line 277, in move_asset
    raise NotAnAssetError(f"No such asset: {src}.")
onyo.lib.exceptions.NotAnAssetError: No such asset: /Users/tkadelka/onyo/a/b/c.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tkadelka/INM7/onyo/onyo/main.py", line 301, in main
    args.run(args)
  File "/Users/tkadelka/INM7/onyo/onyo/commands/mv.py", line 44, in mv
    onyo_mv(inventory=inventory,
  File "/Users/tkadelka/INM7/onyo/onyo/lib/commands.py", line 536, in onyo_mv
    move_asset_or_dir(inventory, sources[0], destination.parent)
  File "/Users/tkadelka/INM7/onyo/onyo/lib/commands.py", line 495, in move_asset_or_dir
    inventory.move_directory(source, destination)
  File "/Users/tkadelka/INM7/onyo/onyo/lib/inventory.py", line 409, in move_directory
    raise ValueError(f"Target {dst / src.name} already exists.")
ValueError: Target /Users/tkadelka/onyo/a/d/c already exists.
```

**Comment by bpoldrack** [comment]
I do not consider this a bug ATM. Tests explicitly demand that a move where the basename of source and destination are equal (`c` in this case), the destination is to be interpreted as the "full" target path, not just the dir to put it in.

So, `onyo mv some/thing elsewhere/thing` is explicitly saying `some/thing -> elsewhere/thing` rather than `some/thing -> elsewhere/thing/thing`.

**Comment by TobiasKadelka** [comment]
From my POV this is a bug in code and test together then🤔

I do not see any reason why this should not work in Onyo. When we allow multiple directories to have the same name, there is no obvious reason to not follow the behavior of the classical mv command for this szenario.

**Comment by bpoldrack** [comment]
Well, we could change that, of course.

Trouble from my POV: Such a command becomes ambiguous. `mv a/b c/b` has no clear meaning then. It results in `c/b` if that didn't exist before and `c/b/b` otherwise. I don't think that's nice. And it's not made better b/c `mv` does it, too.
