### ISSUE TITLE
 BUG: `onyo unset` and `onyo_unset()` do not check for `path` in keys to unset

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#528]
The call of `onyo unset --keys path` errors, which is technically correct, but IMO it does not error nicely (e.g. it gives no explainatory message), and probably just "accidently": it states a `KeyError` (named properly enough) was raised because "path" is not in the asset file, but gives no further context.

For context: Normally, non-existing keys do not raise a `KeyError` in `onyo unset`, they just trigger a debug message.
Other commands (e.g. edit) state explicitly that "path" is not allowed.

There are IMO two ways to solve this and normalize the behavior:
1. there could be an explicite error when `onyo unset --keys path` (like for other commands when called with "path")
2. a debug message could be printed when called with "path" (like for other non-existing keys for `onyo unset`)

-------------

Here the behavior that currently seems incorrect to me:

```
(valid) tkadelka in ~/onyo on git:master
❱ onyo unset --keys path                                                                   1 !
ERROR: 'path'

(valid) tkadelka in ~/onyo on git:master
❱ onyo --debug unset --keys path a_a_a.fauxKJG3b9                                          1 !
DEBUG:onyo:Onyo repo found at '/Users/tkadelka/onyo'
DEBUG:onyo:Running 'git config --get onyo.assets.filename'
DEBUG:onyo:git config missed 'onyo.assets.filename'
DEBUG:onyo:Running 'git config --file /Users/tkadelka/onyo/.onyo/config --get onyo.assets.filename'
DEBUG:onyo:config 'onyo.assets.filename' acquired from /Users/tkadelka/onyo/.onyo/config: '{type}_{make}_{model}.{serial}'
DEBUG:onyo:Running 'git config --get onyo.assets.filename'
DEBUG:onyo:git config missed 'onyo.assets.filename'
DEBUG:onyo:Running 'git config --file /Users/tkadelka/onyo/.onyo/config --get onyo.assets.filename'
DEBUG:onyo:config 'onyo.assets.filename' acquired from /Users/tkadelka/onyo/.onyo/config: '{type}_{make}_{model}.{serial}'
DEBUG:onyo:Looking up tracked files
DEBUG:onyo:Running 'git ls-files -z'
DEBUG:onyo:a_a_a.fauxKJG3b9 not in {'type': 'a', 'make': 'qwerty', 'model': 'as df', 'serial': 'fauxmnU3e4', 'key': 'value', 'path': PosixPath('/Users/tkadelka/onyo/a/a_qwerty_as df.fauxmnU3e4')}
ERROR: 'path'
DEBUG:onyo:Traceback (most recent call last):
  File "/Users/tkadelka/INM7/onyo/onyo/main.py", line 301, in main
    args.run(args)
  File "/Users/tkadelka/INM7/onyo/onyo/commands/unset.py", line 69, in unset
    unset_cmd(inventory,
  File "/Users/tkadelka/INM7/onyo/onyo/lib/commands.py", line 1017, in onyo_unset
    new_content.pop(k)
  File "/Users/tkadelka/env/valid/lib/python3.12/site-packages/ruamel/yaml/comments.py", line 924, in pop
    result = self[key]
             ~~~~^^^^^
  File "/Users/tkadelka/env/valid/lib/python3.12/site-packages/ruamel/yaml/comments.py", line 851, in __getitem__
    return ordereddict.__getitem__(self, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'path'
```

Trying to unset name fields errors nicely:
```
(valid) tkadelka in ~/onyo on git:master
❱ onyo unset --keys type                                                                 130 !
ERROR: Can't unset asset name keys.

```

**Comment by bpoldrack** [comment]
> Trying to unset name fields errors nicely

I think that's exactly how it should fail. Just that it's about pseudo-keys in this case. Same goes for `set`, of course.
